siteconfig.content:
  path: '/json_pagetype/{api_key}/{node}'
  defaults:
    _controller: '\Drupal\site_config\Controller\SiteConfigController::content'
  requirements:
    _permission: 'access content'